In [2]:
import numpy as np
import cvxpy as cp
import scipy as sp

In [3]:
graph = np.random.randint(0, 2, (4, 4))
graph = graph.T * graph
num_rows, num_columns = graph.shape
for i in range(num_rows):
  graph[i][i] = 1
print(graph)


[[1 1 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [4]:
start_nodes = np.random.randint(low = 0, high = 2, size = (4, 4))
print(start_nodes)

[[1 0 0 1]
 [1 0 0 1]
 [1 1 0 1]
 [0 1 0 1]]


In [5]:
start_times = np.random.randint(0, 3, size=(3,))
f = []
t = 3
p = 3
for i in range(t):
  sub_f = []
  for j in range(p):
    sub_f.append(cp.Variable((4, 4), boolean=True))
  f.append(sub_f)


In [6]:
constraints = []
constraint1 = 0
for i in range(t):
  for j in range(p):
    constraint1 += f[i][j]
  constraints.append(constraint1 <= 1)

In [7]:
constraint2 = 0
constraint3 = 0
for i in range(p):
  for j in range(start_times[i]+1):
    constraint2 += f[i][j]
  constraints.append(constraint2 == 0)
  for j in range(start_times[i] + 1, t):
    constraint3 += f[i][j]
  constraints.append(constraint3 <= 1)


In [8]:
objective = 0
for i in range(1, t):
  for j in range(1, p):
    objective = objective + sum(sum(f[i][j]))
objective.shape

()

In [9]:
print(cp.installed_solvers())

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']


In [11]:
problem = cp.Problem(cp.Maximize(objective), constraints)
problem.solve(solver = 'GLPK_MI',  verbose=True)
print("Status: ", problem.status)
print("Optimal value: ", problem.value)
counter = 0
for i in range(t):
  print("Time slot #{}".format(i))
  for j in range(p):
    print("Request #{}".format(j))
    print(f[i][j].value)


                                     CVXPY                                     
                                     v1.2.2                                    
(CVXPY) Dec 15 08:31:13 AM: Your problem has 144 variables, 9 constraints, and 0 parameters.
(CVXPY) Dec 15 08:31:13 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Dec 15 08:31:13 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Dec 15 08:31:13 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Dec 15 08:31:13 AM: Compiling problem (target solver=GLPK_MI).
(CVXPY) Dec 15 08:31:13 AM: Reduction chain: FlipObjective -> Dcp2Cone -> CvxAttr2Constr -> 